In [ ]:
# Numpy - Numeric Python
# Most powerful package - Library

# Numpy - Dimensions

# A - One Dimensional Array
# [A,B] || [A
#          B] - Two Dimensional Array - Row ||column

# Three Dimensional

# Array - storing, manupulating, similar Data type
# Faster than any mathematical functions
# Convinient compared to otther packages
# Memory efficiency
# support multidimensional arrays


# speed(Numpy operations) > speed(Lists operations)
# size(Numpy operations) > size(Lists operations)
# Memory optimization(Numpy) > Memory Optimizations(List operations)

In [ ]:
# Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
arr2D = np.array([
    [1,2,3],[4,5,6]
    ])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
# creating arrays with default values

# creating matrix with all values of elements as '0'
allzeros = np.zeros((2,3))
print(allzeros)
# creating matrix with all values of elements as '1'
allones = np.ones((2,3))
print(allones)
# creating matrix with all values of elements as 'n'
allconstant = np.full((2,3),6)
print(allconstant)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
# create an identity matrix - I

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A belongs to R MxN
# aIJ -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating random Matrices

# with 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(7,7))
print(rand2)

[[0.18842049 0.95571544 0.15392327]
 [0.48879501 0.50822311 0.03546732]
 [0.80433667 0.46903614 0.13285215]]
[[12 16 12 13 14 14 18]
 [19 12 15 17 18 11 18]
 [10 18 15 19 12 14 18]
 [11 19 17 13 17 10 14]
 [18 12 16 19 12 11 19]
 [19 12 11 18 15 12 18]
 [15 15 16 17 19 15 18]]


In [ ]:
# Array properties
arr = np.array([[1,9,8,9],[0,3,4,5]])
print(arr)

# Shape of array
print(f'The shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# DataType of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The dimension of the array is {arr.ndim}')


[[1 9 8 9]
 [0 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The dimension of the array is 2


In [ ]:
# Indexing and Slicing

# Access the elements in 1D Array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the elements in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # First row with all columns
print(arr2[:,0]) # First column with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
#l1 = []
#[l1.append(_) for _ in range(10)]

l1 = np.arange(10,0,-1)

print(l1)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
#Mathematical operations

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

print(f'The su of a and b is {a + b}')
print(f'The diff of a and b is {a - b}')
print(f'The product of a and b is {a * b}')
print(f'The division  of a and b is {a / b}')

The su of a and b is [ 5  7  9 11]
The diff of a and b is [-3 -3 -3 -3]
The product of a and b is [ 4 10 18 28]
The division  of a and b is [0.25       0.4        0.5        0.57142857]


In [ ]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,5],[8,8],[1,1]])

# Dot product    --- product = AB -- A  m x n  -- B n x p
c = np.dot(b1,b2)
print(c)

[[24 24]
 [38 38]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print (b2)

[[5 5]
 [8 8]
 [1 1]]
