<a href="https://colab.research.google.com/github/Raja-NriDegree/Numpy/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr1 = np.random.randint(1,2,(3,1))

In [6]:
arr.shape
arr1.shape

(3, 1)

In [7]:
result = np.dot(arr,arr1)

In [8]:
print(result)

[[ 6]
 [15]]


In [9]:
r1 = np.random.randint(10,20,(3,3))

In [10]:
print(r1)

[[13 10 12]
 [18 12 18]
 [18 12 10]]


In [11]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
result2 = np.eye(3)

In [13]:
print(result2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
t1 =np.random.randint(3,6,(3,3))
t2 =np.random.randint(3,6,(3,3))

In [15]:
print(t1)
print(t2)

[[4 4 5]
 [5 5 4]
 [3 5 4]]
[[3 5 4]
 [5 5 4]
 [4 3 5]]


In [16]:
t3 = (t1) + (t2)

In [17]:
print(t3)

[[ 7  9  9]
 [10 10  8]
 [ 7  8  9]]


In [18]:
t3 = (t1) * (t2)

In [20]:
print(t3)

[[12 20 20]
 [25 25 16]
 [12 15 20]]


In [25]:
mean = t3.mean()
max = t3.max()

In [26]:
print(max)

25


In [27]:
mean = t3.mean()
max = t3.max()
median = np.median(t3)

In [28]:
print(median)

20.0


In [30]:
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)

In [31]:
print(std)

4.642796092394707


In [32]:
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [33]:
print(var)

21.555555555555557


In [34]:
std * std

21.555555555555557

In [56]:
# Trigonometric functions
#  sin(x)
#  Cos(x)
#  Tan(x) - sin(x)/cos(x)
#  Cosec(x)- 1/sin(x)
#  Sec - 1/cos(x)
#  Cot -1/tan(x)

In [58]:
angles = np.array([0,15,30,45,60,75,90])

In [59]:
   result = np.sin(np.radians(angles))
   result1 = np.cos(np.radians(angles))
   result2 = np.tan(np.radians(angles))

In [60]:
print (result)
print (result1)
print (result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [57]:
 arr = np.array([1,2,3,4,5,6])
 reshapedarr = arr.reshape(3,2)

 print(reshapedarr)
 flattendarr = arr.flatten()
 print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [76]:
 arr = np.array([10,20,30,40,50,60,70,80])

 farr = arr[arr > 40]

 print(farr)

[50 60 70 80]
